import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useI18n } from '@/i18n';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/services/supabase';
import PasswordField from '@/components/PasswordField';
import LocationSelect, { EMPTY_LOCATION, type LocationValue } from '@/components/LocationSelect';
import GoogleButton from '@/components/GoogleButton';
import {
  assessPassword, emailError, friendlyAuthError, mobileError, normalizeMobile, toE164,
} from '@/services/validation';

/**
 * Signup.
 *
 * The `profiles` row is created by the handle_new_user trigger, NOT here.
 * first_name / last_name go through auth metadata so the trigger picks them up;
 * everything else is an update afterwards.
 *
 * NOTE: profiles.full_name is a GENERATED column — Postgres composes it from
 * first_name + last_name. Never write to it. The generated types do not mark
 * it read-only, so TypeScript will not stop you; the database will, at runtime.
 */
export default function Signup() {
  const { t, lang } = useI18n();
  const { refreshProfile } = useAuth();
  const navigate = useNavigate();

  const [form, setForm] = useState({
    firstName: '', lastName: '', email: '',
    password: '', confirm: '', mobile: '',
  });
  const [loc, setLoc] = useState<LocationValue>(EMPTY_LOCATION);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [submitted, setSubmitted] = useState(false);

  const set = (k: keyof typeof form) => (e: React.ChangeEvent<HTMLInputElement>) =>
    setForm((f) => ({ ...f, [k]: e.target.value }));

  const mobileDigits = normalizeMobile(form.mobile);
  const errs = {
    firstName: form.firstName.trim() ? null : 'First name is required',
    email: emailError(form.email),
    password: assessPassword(form.password).acceptable ? null : 'Password is not strong enough',
    confirm: form.password === form.confirm ? null : 'Passwords do not match',
    mobile: mobileError(mobileDigits),
    district: loc.district ? null : 'District is required',
    taluka: loc.taluka ? null : 'Taluka is required',
    village: loc.village ? null : 'Village is required',
  };
  const firstProblem = Object.values(errs).find(Boolean) ?? null;

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    setSubmitted(true);
    if (firstProblem) { setError(firstProblem); return; }

    setBusy(true);
    setError(null);

    const { data, error: err } = await supabase.auth.signUp({
      email: form.email.trim(),
      password: form.password,
      options: { data: { first_name: form.firstName.trim(), last_name: form.lastName.trim() } },
    });

    if (err) { setBusy(false); setError(friendlyAuthError(err.message)); return; }

    // Supabase does not error on a duplicate email when email confirmation is
    // on — it returns a user with an empty identities array instead, to avoid
    // leaking which addresses are registered. Detect that and say so.
    if (data.user && (data.user.identities?.length ?? 0) === 0) {
      setBusy(false);
      setError('This email is already registered. Try logging in, or use "Forgot password".');
      return;
    }
    if (!data.user) { setBusy(false); setError(t('common.errorGeneric')); return; }

    // The trigger creates the profiles row; wait for it rather than guessing a
    // delay, then fill in the rest.
    const ok = await waitForProfile(data.user.id);
    if (!ok) {
      setBusy(false);
      setError('Account created, but your profile did not save. Please log in and try again.');
      return;
    }

    const { error: upErr } = await supabase.from('profiles').update({
      // full_name is generated by Postgres from first/last — never set here
      first_name: form.firstName.trim(),
      last_name: form.lastName.trim() || null,
      mobile: toE164(mobileDigits),
      preferred_language: lang,
      village: loc.village,
      taluka: loc.taluka,
      district: loc.district,
      state: loc.state,
      is_profile_complete: true,
    }).eq('id', data.user.id);

    if (upErr) { setBusy(false); setError(upErr.message); return; }

    // Pull the saved row into context NOW. Without this the session still holds
    // the profile as the trigger first wrote it, and the farmer sees blanks
    // until they log out and back in.
    await refreshProfile();

    setBusy(false);
    navigate('/setup/farm', { replace: true });
  }

  const show = (key: keyof typeof errs): string | null =>
    (submitted ? errs[key] : null) ?? null;

  return (
    <div className="mx-auto flex min-h-dvh max-w-md flex-col px-5 pb-10 pt-12">
      <h1 className="text-display">{t('auth.signupTitle')}</h1>

      <div className="mt-6">
        <GoogleButton onError={setError} />
      </div>

      <div className="my-6 flex items-center gap-3">
        <span className="h-px flex-1 bg-hairline" />
        <span className="text-body text-ink-faint">or</span>
        <span className="h-px flex-1 bg-hairline" />
      </div>

      <form onSubmit={onSubmit} noValidate className="space-y-4">
        <div className="grid grid-cols-2 gap-3">
          <Field label={t('auth.firstName')} required value={form.firstName}
                 onChange={set('firstName')} autoComplete="given-name" error={show('firstName')} />
          <Field label={t('auth.lastName')} value={form.lastName}
                 onChange={set('lastName')} autoComplete="family-name" />
        </div>

        <Field label={t('auth.email')} required type="email" inputMode="email"
               value={form.email} onChange={set('email')} autoComplete="email"
               error={show('email')} />

        {/* Mobile: fixed +91, exactly 10 digits, non-digits stripped as typed */}
        <div>
          <label className="mb-1.5 block text-body text-ink-muted">
            {t('auth.mobile')}<span className="text-danger"> *</span>
          </label>
          <div className="flex gap-2">
            <span className="flex h-tap shrink-0 items-center rounded-card border border-hairline bg-raised px-3 text-body text-ink-muted">
              +91
            </span>
            <input
              type="tel" inputMode="numeric" autoComplete="tel-national"
              value={mobileDigits}
              onChange={(e) => setForm((f) => ({ ...f, mobile: normalizeMobile(e.target.value) }))}
              placeholder="9876543210"
              maxLength={10}
              className="field flex-1"
            />
          </div>
          <p className={`mt-1 text-sm ${show('mobile') ? 'text-danger' : 'text-ink-faint'}`}>
            {show('mobile') || `${mobileDigits.length}/10 digits`}
          </p>
        </div>

        <PasswordField
          label={t('auth.password')} required showStrength
          value={form.password}
          onChange={(v) => setForm((f) => ({ ...f, password: v }))}
        />

        <PasswordField
          label="Confirm password" required
          value={form.confirm}
          onChange={(v) => setForm((f) => ({ ...f, confirm: v }))}
          mustMatch={form.password}
          autoComplete="new-password"
        />

        <div className="border-t border-hairline pt-4">
          <LocationSelect value={loc} onChange={setLoc} required />
        </div>

        {error && (
          <p role="alert" className="rounded-card border border-danger/40 bg-danger/10 p-3 text-body text-danger">
            {error}
          </p>
        )}

        <button type="submit" disabled={busy} className="btn-primary">
          {busy ? t('common.loading') : t('auth.signup')}
        </button>
      </form>

      <p className="mt-6 text-center text-body text-ink-muted">
        {t('auth.haveAccount')}{' '}
        <Link to="/login" className="inline-flex h-11 items-center px-2 font-medium text-leaf">{t('auth.login')}</Link>
      </p>
    </div>
  );
}

/** Poll briefly for the row the AFTER INSERT trigger creates. */
async function waitForProfile(userId: string, tries = 10): Promise<boolean> {
  for (let i = 0; i < tries; i += 1) {
    const { data } = await supabase.from('profiles').select('id').eq('id', userId).maybeSingle();
    if (data) return true;
    await new Promise((r) => setTimeout(r, 300));
  }
  return false;
}

function Field({ label, error, required, ...props }: {
  label: string; error?: string | null; required?: boolean;
} & React.InputHTMLAttributes<HTMLInputElement>) {
  return (
    <label className="block">
      <span className="mb-1.5 block text-body text-ink-muted">
        {label}{required && <span className="text-danger"> *</span>}
      </span>
      <input {...props} className="field" />
      {error && <span className="mt-1 block text-sm text-danger">{error}</span>}
    </label>
  );
}
